### ISSUE TITLE
Status of SnoopCompile

### ISSUE THREAD

**Issue by lkapelevich** [timholy/SnoopCompile.jl#29] opened 2019-05-31 19:58 UTC
We are trying to understand how to build a user image in Julia and playing with SnoopCompile/PackageCompiler. There are a couple of things that would be nice to clarify. 

1. We get different precompile statements from SnoopCompile/PackageCompiler [example](https://gist.github.com/lkapelevich/e4f539e7da084240a3c49a76554eb0bc) - why is that?
2. Is it feasible to provide a single way to snoop in the future?
3. What is the recommended way to build a user image from SnoopCompile snoop files? Presumably with PackageCompiler, but this is not documented at the moment. (And currently only @SimonDanisch's sd-notomls branch works for unregistered packages, with a bit of manual editing of snoop files)

cc: @SimonDanisch

**Comment by timholy** [comment] 2019-06-01 12:29
Best guesses:

1. SnoopCompile is careful to launch a new Julia process for the snoop commands. If PackageCompiler isn't, the fact that you already used JLD a bit in the same session means that it will omit the methods that were already compiled. Try again without building your JLD file in the same session.
2. That's more a question for @SimonDanisch since SnoopCompile is the "original."
3. Documented https://github.com/timholy/SnoopCompile.jl#userimgjl

**Comment by lkapelevich** [comment] 2019-06-02 14:53
Thanks for the responses!

Regarding 3 - Oops I have only tried creating images as in https://docs.julialang.org/en/v1/devdocs/sysimg/index.html and didn't realize we can modify base/uerimg.jl.
I now have a usage question... for the example in the gist, building Julia fails with an `UndefVarError` due to the statement `precompile(Tuple{getfield(JLD, Symbol("##s27#8")), Int, Int, Int, Int, Int})` , is that an issue or am I not including something I should be?

Regarding 1- I didn't mean to build the JLDs in the same session, but I did mess something up and the gist is now updated- I am still curious why the precompile statements are different.

**Comment by timholy** [comment] 2019-06-02 18:09
> I now have a usage question... for the example in the gist, building Julia fails with an UndefVarError due to the statement precompile(Tuple{getfield(JLD, Symbol("##s27#8")), Int, Int, Int, Int, Int}) , is that an issue or am I not including something I should be?

Are you using the latest SnoopCompile? #27 should have fixed that. If it didn't, check the code behind that change (it was a simple PR), it should give you hints about what else needs to be fixed. (PR appreciated.)

> In particular, it looks like SnoopCompile generated more precompile statements than PackageCompiler, but if we start a Julia session using the statements from SnoopCompile then --trace-compiles picks up more methods.

I haven't yet played with PackageCompiler myself, so I'm not the right person to answer that.

**Comment by SimonDanisch** [comment] 2019-06-02 19:15
Sorry, @timholy, this was a bit indirect! I didn't really mean to create an alternative to SnoopCompile, but there was a time where SnoopCompile was not working, and I only needed a very small portion of the code to work and couldn't get the whole thing fixed in a PR, so I just used that small bit for PackageCompiler.

By now, I started using `julia --trace-compile=precompiles.jl snoopfile.jl` and only wrote a pretty small wrapper around that for PackageCompiler. Do you know anything about that flag and how it compares to the method used here?

As @lkapelevich pointed out, we observed the odd behaviour, that SnoopCompile seems to record more precompile statements, but using them in a system image actually leads to more JIT overhead than using the fewer ones generated with `--trace-compile`. Even weirder, when merging them, the compilation overhead was identical to the non-merged version generated by `--trace-compile` only.

I was hoping that you may have some insights into this, since I vaguely remember that you were involved in creating those tracing options in Julia! I'd also like to know, why there have been quite some regressions since 0.6 - on 0.6 I was basically able to create JIT free images with SnoopCompile, while on 1.0, lots of compilation is still happening.
If we figure this out, I could put some work into moving the snoop functionality out of PackageCompiler back to its origin ;)

**Comment by timholy** [comment] 2019-06-03 14:26
Oh, no worries, and I'm sorry SnoopCompile wasn't working properly. I just don't know the guts of PackageCompiler, so I couldn't answer the question.

I added `--track-allocation` but not `--trace-compile`. I don't have any insight right now about what's failing. My JuliaCon hackathon project is to sit down with Jameson & finish https://github.com/JuliaLang/julia/pull/31466. That won't immediately help PackageCompiler, as the main goal is to shorten the latency without resorting to PackageCompiler.

Of course for caching native code PackageCompiler is still the best approach. Depending on how things go with that Julia PR we could then sit down and try to figure out some of these other issues?

**Comment by lkapelevich** [comment] 2019-06-04 19:11
> Are you using the latest SnoopCompile? #27 should have fixed that. If it didn't, check the code behind that change (it was a simple PR), it should give you hints about what else needs to be fixed. (PR appreciated.)

Happy to make a PR- is it safe to exclude all statements that contain `##s..#..`? I don't really know how these symbols are generated and I have only seen this pattern from JLD and FowardDiff.

If there are leads on what `--trace-compile` should and should not pick up I would be curious to know :-).

**Comment by timholy** [comment] 2019-06-04 21:02
> is it safe to exclude all statements that contain ##s..#..

I think so. And actually in #27 it looks like changing `\d` -> `\w` will fix your case (try it and see if there are any other problems).

**Comment by SimonDanisch** [comment] 2019-06-04 21:32
> Depending on how things go with that Julia PR we could then sit down and try to figure out some of these other issues?

Sounds great :)

**Comment by lkapelevich** [comment] 2019-06-05 02:34
`\d` -> `\w` removes a bit more than we need, the symbols that caused issues in the example were `"##s27#8"` and `""##all#578""` but a line with `"##load#13"` doesn't seem to cause any errors. Would accounting for each case be a bit too specific? I saw that in PackageCompiler every precompile line is wrapped in a try block.

**Comment by timholy** [comment] 2019-06-05 09:02
Can you do `isdefined(mod, name)` instead? `try`/`catch` is much heavier. These days I also prefer to use `@assert precompile(...)`, e.g., https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/208, and putting things in `try`/`catch` would make that useless.

**Comment by yhls** [comment] 2019-11-13 00:47
I'm seeing anonymous functions like `#attr!##kw` and `#104#105`, which are not caught by `anonrex`. Is it ever possible to create an identifier with `#` in it? If not, maybe it would be reasonable to assume that anything with a hash is something we won't want to precompile.

**Comment by timholy** [comment] 2019-11-13 08:28
Actually, `#attr!##kw` is reproducible so perhaps should be kept. `#104#105` is not reproducible (it depends on module-loading order) so should not be precompiled.

**Comment by yhls** [comment] 2019-11-13 21:12
Ok, sounds like `#attr!##kw` is reasonable to keep around. To catch ones like `#104#105`, what do you think about a regex like `r"#{1,2}[^\"#]+#{1,2}\d+"`? Or if we really want to keep ones like `##load#13` (mentioned above) in case they work, how about `r"#{1,2}\d+#{1,2}\d+"`?

**Comment by timholy** [comment] 2019-11-19 16:05
I don't think `##load#13` works; basically anything with digits is bad.

**Comment by timholy** [comment] 2019-11-19 19:21
I think it's fair to say this was closed by #30 and #31.

**Closed by timholy** 2019-11-19 19:21 UTC
