### ISSUE TITLE
`invalidation_trees` AssertionError: leaf !== nothing

### ISSUE THREAD

**Issue by roflmaostc** [timholy/SnoopCompile.jl#315] opened 2022-11-22 17:17 UTC
Hi,

not quite sure, what's going wrong but while testing [this](https://github.com/bionanoimaging/FourierTools.jl/tree/SnoopPreccompile), I encountered this:

```julia
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [7073ff75] IJulia v1.23.3
  [5fb14364] OhMyREPL v0.5.12
⌃ [c3e4b0f8] Pluto v0.19.15
  [295af30f] Revise v3.4.0
  [aa65fe97] SnoopCompile v2.9.5
  [e2b509da] SnoopCompileCore v2.9.0
⌅ [1e6cf692] TestEnv v1.8.0

(@v1.8) pkg> activate .
  Activating project at `~/.julia/dev/FourierTools.jl`

julia> using SnoopCompileCore

julia> invalidations = @snoopr begin
           # package loads and/or method definitions that might invalidate other code
           using FourierTools
       end
1246-element Vector{Any}:
  MethodInstance for similar(::Type{Array{Union{Int64, Symbol}, _A}}, ::Tuple{Union{Integer, Base.OneTo}}) where _A
 0
  MethodInstance for similar(::Type{Array{Union{Int64, Symbol}, _A}}, ::Tuple{Union{Integer, Base.OneTo}}) where _A
 1
  MethodInstance for similar(::Type{Array{Union{Int64, Symbol}, _A}}, ::Union{Integer, AbstractUnitRange}) where _A
 1
  MethodInstance for Base._array_for(::Type{Union{Int64, Symbol}}, ::Base.HasShape, ::Any)
 2
 u MethodInstance for Base._collect(::Type{Union{Int64, Symbol}}, ::Base.Generator{_A, typeof(identity)} where _A, ::Union{Base.HasLength, Base.HasShape})
 3
  MethodInstance for collect(::Type{Union{Int64, Symbol}}, ::Base.Generator{_A, typeof(identity)} where _A)
 4
  MethodInstance for Base.vectorfilter(::Type{Union{Int64, Symbol}}, ::Base.var"#132#133"{typeof(in), typeof(pop!)}, ::Vector{Union{Int64, Symbol}})
 5
  MethodInstance for Base._shrink(::Function, ::Vector{Union{Int64, Symbol}}, ::Tuple{Vector{Symbol}})
 6
  MethodInstance for intersect(::Vector{Union{Int64, Symbol}}, ::Vector{Symbol})
 7
  MethodInstance for setdiff(::Vector{Union{Int64, Symbol}}, ::Vector{Symbol})
 7
  Tuple{typeof(similar), Type{Array{Union{Int64, Symbol}, _A}} where _A, Tuple{Union{Integer, AbstractUnitRange}}}
 ⋮
 3
  MethodInstance for (::FourierTools.var"#ft_fix_after##kw")(::NamedTuple{(:start_dim,), Tuple{Int64}}, ::typeof(ft_fix_after), ::PaddedViews.PaddedView{ComplexF32, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, OffsetArrays.OffsetMatrix{ComplexF32, ShiftedArrays.CircShiftedArray{ComplexF32, 2, Matrix{ComplexF32}}}}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64})
 4
  MethodInstance for FourierTools.rft_fix_after(::PaddedViews.PaddedView{ComplexF32, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, OffsetArrays.OffsetMatrix{ComplexF32, ShiftedArrays.CircShiftedArray{ComplexF32, 2, Matrix{ComplexF32}}}}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64})
 5
  MethodInstance for FourierTools.var"#ft_fix_after#40"(::Int64, ::typeof(ft_fix_after), ::FourierTools.FourierSplit{ComplexF32, 2, PaddedViews.PaddedView{ComplexF32, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, OffsetArrays.OffsetMatrix{ComplexF32, FourierTools.FourierJoin{ComplexF32, 2, FourierTools.FourierJoin{ComplexF32, 2, ShiftedArrays.CircShiftedArray{ComplexF32, 2, Matrix{ComplexF32}}}}}}}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64})
 3
  MethodInstance for (::FourierTools.var"#ft_fix_after##kw")(::NamedTuple{(:start_dim,), Tuple{Int64}}, ::typeof(ft_fix_after), ::FourierTools.FourierSplit{ComplexF32, 2, PaddedViews.PaddedView{ComplexF32, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, OffsetArrays.OffsetMatrix{ComplexF32, FourierTools.FourierJoin{ComplexF32, 2, FourierTools.FourierJoin{ComplexF32, 2, ShiftedArrays.CircShiftedArray{ComplexF32, 2, Matrix{ComplexF32}}}}}}}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64})
 4
  MethodInstance for FourierTools.rft_fix_after(::PaddedViews.PaddedView{ComplexF32, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, OffsetArrays.OffsetMatrix{ComplexF32, FourierTools.FourierJoin{ComplexF32, 2, FourierTools.FourierJoin{ComplexF32, 2, ShiftedArrays.CircShiftedArray{ComplexF32, 2, Matrix{ComplexF32}}}}}}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64})
 5
  MethodInstance for FourierTools.var"#ft_fix_after#40"(::Int64, ::typeof(ft_fix_after), ::PaddedViews.PaddedView{ComplexF32, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, OffsetArrays.OffsetMatrix{ComplexF32, FourierTools.FourierJoin{ComplexF32, 2, FourierTools.FourierJoin{ComplexF32, 2, ShiftedArrays.CircShiftedArray{ComplexF32, 2, Matrix{ComplexF32}}}}}}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64})
 3
  MethodInstance for (::FourierTools.var"#ft_fix_after##kw")(::NamedTuple{(:start_dim,), Tuple{Int64}}, ::typeof(ft_fix_after), ::PaddedViews.PaddedView{ComplexF32, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, OffsetArrays.OffsetMatrix{ComplexF32, FourierTools.FourierJoin{ComplexF32, 2, FourierTools.FourierJoin{ComplexF32, 2, ShiftedArrays.CircShiftedArray{ComplexF32, 2, Matrix{ComplexF32}}}}}}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64})
 4
  MethodInstance for FourierTools.rft_fix_after(::PaddedViews.PaddedView{ComplexF32, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, OffsetArrays.OffsetMatrix{ComplexF32, FourierTools.FourierJoin{ComplexF32, 2, FourierTools.FourierJoin{ComplexF32, 2, ShiftedArrays.CircShiftedArray{ComplexF32, 2, Matrix{ComplexF32}}}}}}, ::Tuple{Int64, Int64}, ::Tuple{Int64, Int64})
 5
  MethodInstance for convert(::Type{T}, ::T) where T<:(FourierTools.FourierSplit{ComplexF32, 2} where {T, N})
  "jl_insert_method_instance"
  convert(::Type{T}, a::T) where T<:AbstractArray in Base at abstractarray.jl:16
  "jl_method_table_insert"

julia> using SnoopCompile

julia> trees = invalidation_trees(invalidations)
ERROR: AssertionError: leaf !== nothing
Stacktrace:
 [1] invalidation_trees(list::Vector{Any}; exclude_corecompiler::Bool)
   @ SnoopCompile ~/.julia/packages/SnoopCompile/Q8zUg/src/invalidations.jl:365
 [2] invalidation_trees(list::Vector{Any})
   @ SnoopCompile ~/.julia/packages/SnoopCompile/Q8zUg/src/invalidations.jl:294
 [3] top-level scope
   @ REPL[5]:1

julia> versioninfo()
Julia Version 1.8.3
Commit 0434deb161e (2022-11-14 20:14 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 12 × AMD Ryzen 5 5600X 6-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver3)
  Threads: 12 on 12 virtual cores
Environment:
  JULIA_NUM_THREADS = 12

```

Is it my fault somewhere?

Thanks!

Felix

**Comment by MilesCranmer** [comment] 2022-11-27 03:36
Got this too, for DynamicExpressions.jl:

```julia
using SnoopCompile
X = randn(5, 1)

invalidations = @snoopr begin
    using DynamicExpressions
    x1 = Node(Float64; feature=1)
    c1 = Node(Float64; val=1.0)
    tree = Node(1, Node(2, x1), c1)
    operators = OperatorEnum(binary_operators=[+, -, *, /], unary_operators=[exp, sin, cos])
    tree(X)
end;

trees = SnoopCompile.invalidation_trees(invalidations)
```

Output:
```
ERROR: AssertionError: leaf !== nothing
Stacktrace:
 [1] invalidation_trees(list::Vector{Any}; exclude_corecompiler::Bool)
   @ SnoopCompile ~/.julia/packages/SnoopCompile/Q8zUg/src/invalidations.jl:365
 [2] invalidation_trees(list::Vector{Any})
   @ SnoopCompile ~/.julia/packages/SnoopCompile/Q8zUg/src/invalidations.jl:294
 [3] top-level scope
   @ REPL[11]:1
```

**Comment by MilesCranmer** [comment] 2022-11-27 03:44
Tried SnoopCompile 2.8.1, and get this instead:

```
ERROR: unexpected loctag jl_insert_method_instance at 20156
Stacktrace:
 [1] error(::String, ::String, ::String, ::Int64)
   @ Base ./error.jl:44
 [2] invalidation_trees(list::Vector{Any}; exclude_corecompiler::Bool)
   @ SnoopCompile ~/.julia/packages/SnoopCompile/wiBT1/src/invalidations.jl:373
 [3] invalidation_trees(list::Vector{Any})
   @ SnoopCompile ~/.julia/packages/SnoopCompile/wiBT1/src/invalidations.jl:287
 [4] top-level scope
   @ REPL[3]:1
```

**Comment by MilesCranmer** [comment] 2022-11-27 03:46
I just realized this issue is a duplicate of #302 FYI

**Comment by MilesCranmer** [comment] 2022-11-27 03:54
Looks like #302 was solved in https://github.com/SciML/ModelingToolkit.jl/pull/1821 somehow... @ChrisRackauckas @YingboMa @lamorton how did you end up solving it? Sounds like it is known to show up on at least FourierTools.jl, ModelingToolkit.jl, and DynamicExpressions.jl.

**Comment by lamorton** [comment] 2022-11-27 04:09
@MilesCranmer not sure we did anything different. Like I said, it was intermittent, so could still be lurking.

**Comment by MilesCranmer** [comment] 2022-11-27 04:34
By intermittent, do you mean it randomly appears sometimes if you re-run the exact same code on same OS/dependencies/etc, or do you mean it shows up for certain combinations of dependencies?

**Comment by lamorton** [comment] 2022-11-27 04:42
@MilesCranmer I wasn't able to reproduce it on my machine, and on Github it came and went between runs. IDK if the maintainers made any changes on the GH Actions.

**Comment by MilesCranmer** [comment] 2022-11-27 04:47
Thanks! Very weird bug.

Luckily these ones FourierTools.jl and DynamicExpressions.jl seem to be locally reproducible, so maybe the bug can finally be tracked down.

**Comment by roflmaostc** [comment] 2022-11-27 08:27
In my case it seemed to reproducible, the couple of times I checked it.

**Comment by ChrisRackauckas** [comment] 2022-11-27 08:54
I never knew that existed so any fix was accidental.

**Comment by JordiManyer** [comment] 2022-12-26 00:15
I'm having the same issue while tracking invalidations for Gridap.jl. Any progress on what might be going on?

**Comment by timholy** [comment] 2023-01-10 12:56
Not reproducible for me on SnoopCompile 2.9.7 and either Julia 1.8.4 or nightly. Can you still reproduce it?

This package has had many changes and so has Julia. It's worth nothing that 1.8.4 backported some changes from 1.9 in how it handles and logs invalidations, so it's quite possible this is what fixed the bug.

Let me know if you can reproduce this, otherwise I will close.

**Comment by MilesCranmer** [comment] 2023-01-10 13:08
Thanks @timholy. I can report that my issue on DynamicExpressions.jl went away on Julia 1.9.0-beta2 with SnoopCompile 2.9.7! Everything works smoothly now 🎉

**Comment by JordiManyer** [comment] 2023-01-10 14:13
Thanks @timholy. The issue has also been resolved on Gridap.jl using SnoopCompile 2.9.7 and Julia 1.8.5. Thanks to everybody who has been contributing to this!

**Comment by timholy** [comment] 2023-01-10 14:26
Thanks for the feedback!

**Closed by timholy** 2023-01-10 14:26 UTC
